language: cpp

install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then travis_terminate 0; fi

stages:
  - name: Build

jobs:
  include:
    - stage: "Build"
      name: "build all targets"
      script:
        - docker build -t cpp .
        - docker run cpp
      if: |
        (type = push)
